//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Category.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

public class Category {
	public Object categorycode;
	public String name;
	public String getCode() {
	return "Code";
	}
	
	public void setCode(Object String) {
	
	}
	
	public void Operation1() {
	
	}
}
