//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : POLineItems.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.model;


public class POLineItems {
	@SuppressWarnings("unused")
	private String productid;
	public String vendorname;
	public Integer Quantity;
	public String getProductid() {
	return "id";
	}
	
	public void setProductid(Object String) {
	
	}
	
	public String getVendorname() {
	return "VendorName";
	}
	
	public void setVendorname(Object String) {
	
	}
	
	public Integer getQuantity() {
	return 1;
	}
	
	public void setQuantity(Object Int) {
	
	}
}
