//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : product.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.model;


public class Product {
	public String productid;
	public String name;
	public String description;
	public String quantity;
	public String price;
	public String barcodenumber;
	public Integer threshold;
	public Integer orderquantity;
	public String getProductId() {
	return "ProductId";
	}
	
	public void setProductId(Object String) {
	
	}
	
	public String getName() {
	return "Name";
	}
	
	public void setName(Object String) {
	
	}
	
	public String getDescription() {
	return "Desc";
	}
	
	public void setDescription(Object String) {
	
	}
	
	public String getQuantity() {
	return "Quantity";
	}
	
	public void setQuantity(Object String) {
	
	}
	
	public String getPrice() {
	return "Price";
	}
	
	public void setPrice(Object String) {
	
	}
	
	public String getBarcodenumber() {
	return "Barcodenumber";	
	}
	
	public void setBarcodenumber(Object String) {
	
	}
	
	public Integer getThreshold() {
	return 1;
	}
	
	public void setThreshold(Object Int) {
	
	}
	
	public Integer getQrderQuantity() {
	return 1;
	}
	
	public void setOrderQuantity(Object Int) {
	
	}
	
	public String generateProductId(Object String) {
	return "prodid";
	}
	
	public String toString() {
	return "string";
	}
}
