//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PurchaseOrder.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.model;

import java.util.ArrayList;
import java.util.List;

public class PurchaseOrder {
	private List<POLineItem> poLineItems = new ArrayList<POLineItem>();
	private String categoryCode;
	private ArrayList<Vendor> vendorList = new ArrayList<Vendor>();

	public PurchaseOrder() {
		super();
		// TODO Auto-generated constructor stub
	}

	public PurchaseOrder(List<POLineItem> poLineItems,String categoryCd,ArrayList<Vendor> vList) {
		super();
		if (poLineItems!= null) {
			this.poLineItems = poLineItems;
		}
		this.categoryCode = categoryCd;
		this.vendorList = vList;
	}

	public void addPoLineItem(POLineItem item) {
     poLineItems.add(item);
	}

	public String toString() {
		return "String";
	}

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public ArrayList<Vendor> getVendorList() {
		return vendorList;
	}

	public void setVendorList(ArrayList<Vendor> vendorList) {
		this.vendorList = vendorList;
	}
}

