//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PurchaseOrder.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.model;

public class PurchaseOrder {
	public void addPoLineItem(Object PoLineItem) {
	
	}
	
	public String toString() {
	return "String";
	}
}
