//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PurchaseOrder.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.model;

import java.util.List;

public class PurchaseOrder {
	private List<POLineItem> poLineItems;

	public PurchaseOrder() {
		super();
		// TODO Auto-generated constructor stub
	}

	public PurchaseOrder(List<POLineItem> poLineItems) {
		super();
		this.poLineItems = poLineItems;
	}

	public void addPoLineItem(POLineItem item) {
     poLineItems.add(item);
	}

	public String toString() {
		return "String";
	}
}

