//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

public class Transaction {
	@SuppressWarnings("unused")
	private int transactionid;
	@SuppressWarnings("unused")
	private void addTransactionLineItem(Object TransactionLineItem) {
	
	}
}
