//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transaction.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

import java.util.List;

public class Transaction {

	private int transactionId;
    private List<TransactionLineItem> items;
    
    public Transaction() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Transaction(int transactionId, List<TransactionLineItem> items) {
		super();
		this.transactionId = transactionId;
		this.items = items;
	}

	public int getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public List<TransactionLineItem> getItems() {
		return items;
	}

	public void setItems(List<TransactionLineItem> items) {
		this.items = items;
	}

	public void addTransactionLineItem(TransactionLineItem txnLineitem) {
     items.add(txnLineitem);
	}
}

