//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TransactionLineItems.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

import java.util.Date;

public class TransactionLineItem {

	private String productId;
	private String memberId;
	private int quantity;
	private Date txnDate;

	public TransactionLineItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	public TransactionLineItem(String productId, String memberId, int quantity,
			Date txnDate) {
		super();
		this.productId = productId;
		this.memberId = memberId;
		this.quantity = quantity;
		this.txnDate = txnDate;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getMemberId() {
		return memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getTxnDate() {
		return txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

}

