//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TransactionLineItems.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

import java.util.Date;

public class TransactionLineItems {
	public String productid;
	public String memberid;
	public int quantity;
	public Date txndate;
}
