//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vendor.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

public class Vendor {
	public void getName() {
	
	}
	
	public void setName() {
	
	}
	
	public void getDescription() {
	
	}
	
	public void setDescription() {
	
	}
}
