//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vendor.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.model;

public class Vendor {
	private String vendorName;
	private String vendorDescription;

	public Vendor() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Vendor(String vendorName, String vendorDescription) {
		super();
		this.vendorName = vendorName;
		this.vendorDescription = vendorDescription;
	}

	public String getVendorName() {
		return vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	public String getVendorDescription() {
		return vendorDescription;
	}

	public void setVendorDescription(String vendorDescription) {
		this.vendorDescription = vendorDescription;
	}

}

