//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MainMenuUI.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.ui;

public class MainMenuUI {

	public void memeberManagement() {
	
	}
	
	public void stockmanagement() {
	
	}
	
	public void billingManagement() {
	
	}
	
	public void reportmanagement() {
	
	}
}
