//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViewCategoryUI.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.ui;

public class ViewCategoryUI {

	public void memberName() {
	
	}
}
