//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillingManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

import ft.team1.se21.model.Product;

public class BillingManager {
	public Product getproductDetails(Object String) {
	return new Product();
	}
}
