//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CategoryManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

import ft.team1.se21.model.Category;

public class CategoryManager {
	public Object memberName;
	public Category getCategories() {
	return new Category();
	}
	
	public void addCategory(Category category) {
	
	}
	
	public void generateReport() {
	
	}
	
	public void createVendorFile(Object String) {
	
	}
	
	public Category getCategory(Object String) {
	return new Category();
	}
}
