//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CheckOutManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

public class CheckOutManager {
	public void checkMemberDetails(String member){
	
	}
	
	public void redeemPoints(String points){
	
	}
	
	public void generateBillForMembers() {
	
	}
	
	public void generateBillForNonMembers() {
	
	}
}
