//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DiscountHelper.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.manager;


public class DiscountHelper {
	public void getDiscount(Object TransactionManager, Object memberid) {
	
	}
}
