//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InventoryManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

import ft.team1.se21.model.Product;

public class InventoryManager {
	public Object memberName;
	public Product getProductbelowThreshold() {
	return new Product();
	}
	
	public void generatePO(Object Products[]) {
	
	}
}
