//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoginHandler.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

public class LoginHandler {
	public void showLoginUI() {
	
	}
	
	public Boolean validateUser(Object userName, Object password) {
		
		return true;
	
	}
}
