//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//

package ft.team1.se21.manager;


public class MemberManager {
	public Object memberName;
	public void addMember(Object Member) {
	
	}
	
	public void validateMember(Object String) {
	
	}
	
	public int getPoints(Object String) {
	
		return 1;
	}
	
	public void generateReport() {
	
	}
}
