//

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

import java.util.ArrayList;

import ft.team1.se21.model.Category;
import ft.team1.se21.model.Product;

public class ProductManager {
	public Category getProductCategories() {
	return new Category();
	}
	
	public void addProduct(Object Product) {
	
	}
	
	public ArrayList<Product> getProductsToOrder() {
	return new ArrayList<Product>();
	}
	
	public Product getProduct(String productId){
		return new Product();
	}
	
	public void generateReport() {
	
	}
}
