//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReportGenerator.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

public class ReportGenerator {
	public void generateReport(Object String) {
	
	}
	
	public void generateTransactionReport(Object startDate, Object endDate) {
	
	}
}
