//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TransactionManager.java
//  @ Date : 3/16/2013
//  @ Author : 
//
//


package ft.team1.se21.manager;

public class TransactionManager {
	public void isFirstTimeMember() {
	
	}
	
	public void generateTransactionReport(Object startDate, Object endDate) {
	
	}
	
	public void addTransaction(Object param1, Object param2, Object param3, Object param4) {
	
	}
}
